/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FxCounter {
        "values": Array<number>;
    }
}
declare global {
    interface HTMLFxCounterElement extends Components.FxCounter, HTMLStencilElement {
    }
    var HTMLFxCounterElement: {
        prototype: HTMLFxCounterElement;
        new (): HTMLFxCounterElement;
    };
    interface HTMLElementTagNameMap {
        "fx-counter": HTMLFxCounterElement;
    }
}
declare namespace LocalJSX {
    interface FxCounter {
        "values"?: Array<number>;
    }
    interface IntrinsicElements {
        "fx-counter": FxCounter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fx-counter": LocalJSX.FxCounter & JSXBase.HTMLAttributes<HTMLFxCounterElement>;
        }
    }
}
